version: '3.8'

services:
  job-db:
    container_name: job-db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./sql:/home/sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
  job-service:
    build: .
    container_name: job-service
    restart: always
    ports:
      - "8082:8080"
    depends_on:
      - job-db

volumes:
  postgres_data:

