server:
  port: 8082


spring:
  application:
    name: job
  datasource:
    url: jdbc:postgresql://job-db/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  jackson:
    serialization:
      fail-on-empty-beans: false
  graphql:
    path: /job
    graphiql:
      enabled: true
      path: /graphiql
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/jobrealm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
